language: java
jdk: oraclejdk8

services:
        - docker

before_install:
        - sudo service mysql stop
        - docker pull takimatraining/devops-training-db
        - docker run -d -p 127.0.0.01:3306:3306 takimatraining/devops-training-db

script:
        - mvn verify
