language: java
jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"

env:
  global:
  - "w4L9bJZK8DM9NMDB7KAmZwmTBKMBX/uNmIFzEs6mR2nsxSj8hu2kRpYofL9GZqhoe3lVIbrYJT42PKG0M9swWHT3F8v4pzVAx3ovgTMnTVwwLcOBSItX9RemcAh7QNswyT6W1rarufE2afIMFL+WuDLs8nzBxX3u5PXw+0ePzdZ09NTx6O2RwtFI+sM/X3gBOx/EMDFYdGna0AGnG9nyMOWLZBa/5T8eGErTG9cCHr2Gql+uPTbH4/g2TM5VygH5VRQTKXf6U5MfjsXRz+SJ4AFjo8h7+FZjUWgVeCPa8m6IUCDwENbwO2oVtzm3PjEo5ZztNcRRMLiLMfOlUCXWXKoKx3V2iM5+wD8LNlT7+keHpI5rb1LpWdiwAAaIq7PGNe/mk+b3lFd7c+rC+QCsoQzK2MFq7Z09GKVC8fA9NfvlgtCcoriKR23JjI+D1eOcRD4yR339F9dheM0/j3vYgrE8bdReNX3fVDGW9Ut4wAAlXLU+CUX5Diy9pS7+U4QJRHnH2KyduIYl2fvXBfWR5LVtsw9d/UsZdRMgx1qrvlmufQFm5uOGlXSHFnYfNKMMJ3AchZd9MHo3hcs0sxhyH6AG1U9sl7lOmfuakHlHqUkLcsQY+ufewC7dckTqoIWATTnAL9wJjVLrultX/InMOHPcfh2I0VYyFI7o/Fn8XJU="

services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.01:3306:3306 takimatraining/devops-training-db

script:
  - mvn sonar:sonar \
    -Dsonar.projectKey=temion_sample-application-students \
    -Dsonar.organization=temion-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=985a43043526ccb244bf56b2121944a41cac1545
  - mvn clean verify
